image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip setuptools wheel
  - pip install --only-binary=:all: matplotlib
  - pip install -r requirements.txt

# Установите режим сборки на Script
build_script:
  - echo "Skipping Visual Studio build, proceeding with script build."

# Пропуск тестов, если их нет
test_script:
  - echo "Skipping tests..."

# После успешной сборки
after_build:
  - ps: Invoke-RestMethod -Uri "https://api.render.com/deploy/srv-cruo4n68ii6s739up3ag?key=fXIcrHycQlI" -Method Post
