image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip setuptools wheel
  - pip install --only-binary=:all: matplotlib
  - pip install -r requirements.txt

build: off

test_script:
  - python -m unittest discover
