image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip setuptools wheel
  - pip install --only-binary=:all: matplotlib
  - pip install -r requirements.txt

build:
  mode: script  # Изменяем режим сборки на "script"
  script: python app.py  # Указываем команду для запуска вашего приложения

test_script:
  - echo "Skipping tests..."

after_build:
  - ps: Invoke-RestMethod -Uri "https://api.render.com/deploy/srv-cruo4n68ii6s739up3ag?key=fXIcrHycQlI" -Method Post
