image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip setuptools wheel
  - pip install --only-binary=:all: matplotlib
  - pip install -r requirements.txt

build: off

test_script:
  - python -m unittest discover

after_build:
  - ps: Write-Host "Отправка запроса на деплой на Render..."
  - ps: Invoke-RestMethod -Uri "https://api.render.com/deploy/srv-cruo4n68ii6s739up3ag?key=fXIcrHycQlI" -Method Post
